version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: dev
    volumes:
      - ./api:/opt/app/api

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=toor
      - MONGO_INITDB_ROOT_PASSWORD=passdorw
    ports:
      - 27017:27017
